### ISSUE TITLE
Additional info for README

### ISSUE THREAD

**Issue by jmynes** [Acimut/Custom-EV-IV-Display-Screen#4]
It is unclear without context as a new user that the language is set from `main_eviv.c`, rather than from `config.mk`
Can this be made more clear from the README?

------

No está claro sin contexto como nuevo usuario que el idioma se establece desde `main_eviv.c`, en lugar de `config.mk`
¿Puede esto quedar más claro en el README?

**Comment by Acimut** [comment]
An update has been prepared with several changes, within which better explanations are added in the README.

Also, an English version of README is added, if something is wrong feel free to correct it.
